kcptun-openvpn:
  image: vmlinz/kcptun
  ports:
    - "4911:38081/udp"
  environment:
    - KEY=canter-urania-seres-les-blame-sonnet-yan
    - LISTEN_PORT=38081
    - TARGET_PORT=1194
    - TARGET_ADDR=openvpn-server
  links:
    - openvpn
  restart: always

openvpn:
  image: kylemanna/openvpn
  ports:
    - "1194:1194/udp"
    - "1194:1194/tcp"
  volumes:
    - ./openvpn:/etc/openvpn
  cap_add:
    - NET_ADMIN
  restart: always
